/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'guidanceLevel' : string,
  'delayDays' : [] | [bigint],
  'reasoning' : string,
  'isNormal' : boolean,
  'guidance' : string,
}
export interface ChatMessage {
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export interface CyclePrediction {
  'currentPhase' : string,
  'ovulationDate' : string,
  'dayOfCycle' : bigint,
  'fertileWindowStart' : string,
  'fertileWindowEnd' : string,
  'nextPeriodStart' : string,
}
export interface CycleRecord {
  'id' : string,
  'periodDays' : bigint,
  'cycleLengthDays' : bigint,
  'createdAt' : bigint,
  'notes' : [] | [string],
  'startDate' : string,
}
export interface DailyLog {
  'id' : string,
  'painLevel' : [] | [bigint],
  'date' : string,
  'mood' : [] | [string],
  'createdAt' : bigint,
  'notes' : [] | [string],
  'symptoms' : Array<string>,
}
export interface MonthlyReport {
  'nextSteps' : string,
  'avgPainLevel' : number,
  'patternInsight' : string,
  'cycleLength' : bigint,
  'commonSymptoms' : Array<string>,
}
export interface ProfileUpdate {
  'age' : [] | [bigint],
  'dob' : [] | [string],
  'heightCm' : [] | [number],
  'city' : [] | [string],
  'name' : [] | [string],
  'lifeStage' : [] | [string],
  'weightKg' : [] | [number],
}
export interface QuizQuestion {
  'id' : string,
  'question' : string,
  'correctIndex' : bigint,
  'explanation' : string,
  'options' : Array<string>,
}
export interface QuizResult {
  'explanation' : string,
  'correct' : boolean,
  'pointsEarned' : bigint,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface SelfCareItem {
  'title' : string,
  'tips' : Array<string>,
  'description' : string,
  'category' : string,
  'phase' : string,
}
export interface UserProfile {
  'id' : Principal,
  'age' : bigint,
  'dob' : [] | [string],
  'heightCm' : number,
  'city' : string,
  'name' : string,
  'createdAt' : bigint,
  'lifeStage' : string,
  'weightKg' : number,
}
export interface UserProgress {
  'lastQuizDate' : string,
  'totalCompleted' : bigint,
  'quizzesCompletedToday' : bigint,
  'totalPoints' : bigint,
}
export interface _SERVICE {
  'addCycleRecord' : ActorMethod<[CycleRecord], Result>,
  'analyzeCurrentCycle' : ActorMethod<[], AnalysisResult>,
  'getAverageCycleLength' : ActorMethod<[], number>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getCurrentCyclePrediction' : ActorMethod<[], [] | [CyclePrediction]>,
  'getCycleHistory' : ActorMethod<[], Array<CycleRecord>>,
  'getDailyLogs' : ActorMethod<[string, string], Array<DailyLog>>,
  'getDailyQuizzes' : ActorMethod<[], Array<QuizQuestion>>,
  'getLogForDate' : ActorMethod<[string], [] | [DailyLog]>,
  'getMonthlyReport' : ActorMethod<[], MonthlyReport>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSelfCareForPhase' : ActorMethod<[string], Array<SelfCareItem>>,
  'getUserProgress' : ActorMethod<[], UserProgress>,
  'saveDailyLog' : ActorMethod<[DailyLog], Result>,
  'saveProfile' : ActorMethod<[UserProfile], Result>,
  'sendChatMessage' : ActorMethod<[string], string>,
  'submitQuizAnswer' : ActorMethod<[string, bigint], QuizResult>,
  'updateProfile' : ActorMethod<[ProfileUpdate], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];