/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CycleRecord = IDL.Record({
  'id' : IDL.Text,
  'periodDays' : IDL.Nat,
  'cycleLengthDays' : IDL.Nat,
  'createdAt' : IDL.Int,
  'notes' : IDL.Opt(IDL.Text),
  'startDate' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const AnalysisResult = IDL.Record({
  'guidanceLevel' : IDL.Text,
  'delayDays' : IDL.Opt(IDL.Int),
  'reasoning' : IDL.Text,
  'isNormal' : IDL.Bool,
  'guidance' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const CyclePrediction = IDL.Record({
  'currentPhase' : IDL.Text,
  'ovulationDate' : IDL.Text,
  'dayOfCycle' : IDL.Nat,
  'fertileWindowStart' : IDL.Text,
  'fertileWindowEnd' : IDL.Text,
  'nextPeriodStart' : IDL.Text,
});
export const DailyLog = IDL.Record({
  'id' : IDL.Text,
  'painLevel' : IDL.Opt(IDL.Nat),
  'date' : IDL.Text,
  'mood' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'notes' : IDL.Opt(IDL.Text),
  'symptoms' : IDL.Vec(IDL.Text),
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'explanation' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const MonthlyReport = IDL.Record({
  'nextSteps' : IDL.Text,
  'avgPainLevel' : IDL.Float64,
  'patternInsight' : IDL.Text,
  'cycleLength' : IDL.Nat,
  'commonSymptoms' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'age' : IDL.Nat,
  'dob' : IDL.Opt(IDL.Text),
  'heightCm' : IDL.Float64,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'lifeStage' : IDL.Text,
  'weightKg' : IDL.Float64,
});
export const SelfCareItem = IDL.Record({
  'title' : IDL.Text,
  'tips' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : IDL.Text,
  'phase' : IDL.Text,
});
export const UserProgress = IDL.Record({
  'lastQuizDate' : IDL.Text,
  'totalCompleted' : IDL.Nat,
  'quizzesCompletedToday' : IDL.Nat,
  'totalPoints' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'explanation' : IDL.Text,
  'correct' : IDL.Bool,
  'pointsEarned' : IDL.Nat,
});
export const ProfileUpdate = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'dob' : IDL.Opt(IDL.Text),
  'heightCm' : IDL.Opt(IDL.Float64),
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'lifeStage' : IDL.Opt(IDL.Text),
  'weightKg' : IDL.Opt(IDL.Float64),
});

export const idlService = IDL.Service({
  'addCycleRecord' : IDL.Func([CycleRecord], [Result], []),
  'analyzeCurrentCycle' : IDL.Func([], [AnalysisResult], []),
  'getAverageCycleLength' : IDL.Func([], [IDL.Float64], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getCurrentCyclePrediction' : IDL.Func(
      [],
      [IDL.Opt(CyclePrediction)],
      ['query'],
    ),
  'getCycleHistory' : IDL.Func([], [IDL.Vec(CycleRecord)], ['query']),
  'getDailyLogs' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DailyLog)],
      ['query'],
    ),
  'getDailyQuizzes' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getLogForDate' : IDL.Func([IDL.Text], [IDL.Opt(DailyLog)], ['query']),
  'getMonthlyReport' : IDL.Func([], [MonthlyReport], []),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSelfCareForPhase' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SelfCareItem)],
      ['query'],
    ),
  'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
  'saveDailyLog' : IDL.Func([DailyLog], [Result], []),
  'saveProfile' : IDL.Func([UserProfile], [Result], []),
  'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'submitQuizAnswer' : IDL.Func([IDL.Text, IDL.Nat], [QuizResult], []),
  'updateProfile' : IDL.Func([ProfileUpdate], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CycleRecord = IDL.Record({
    'id' : IDL.Text,
    'periodDays' : IDL.Nat,
    'cycleLengthDays' : IDL.Nat,
    'createdAt' : IDL.Int,
    'notes' : IDL.Opt(IDL.Text),
    'startDate' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const AnalysisResult = IDL.Record({
    'guidanceLevel' : IDL.Text,
    'delayDays' : IDL.Opt(IDL.Int),
    'reasoning' : IDL.Text,
    'isNormal' : IDL.Bool,
    'guidance' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const CyclePrediction = IDL.Record({
    'currentPhase' : IDL.Text,
    'ovulationDate' : IDL.Text,
    'dayOfCycle' : IDL.Nat,
    'fertileWindowStart' : IDL.Text,
    'fertileWindowEnd' : IDL.Text,
    'nextPeriodStart' : IDL.Text,
  });
  const DailyLog = IDL.Record({
    'id' : IDL.Text,
    'painLevel' : IDL.Opt(IDL.Nat),
    'date' : IDL.Text,
    'mood' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'notes' : IDL.Opt(IDL.Text),
    'symptoms' : IDL.Vec(IDL.Text),
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'explanation' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const MonthlyReport = IDL.Record({
    'nextSteps' : IDL.Text,
    'avgPainLevel' : IDL.Float64,
    'patternInsight' : IDL.Text,
    'cycleLength' : IDL.Nat,
    'commonSymptoms' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'age' : IDL.Nat,
    'dob' : IDL.Opt(IDL.Text),
    'heightCm' : IDL.Float64,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'lifeStage' : IDL.Text,
    'weightKg' : IDL.Float64,
  });
  const SelfCareItem = IDL.Record({
    'title' : IDL.Text,
    'tips' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : IDL.Text,
    'phase' : IDL.Text,
  });
  const UserProgress = IDL.Record({
    'lastQuizDate' : IDL.Text,
    'totalCompleted' : IDL.Nat,
    'quizzesCompletedToday' : IDL.Nat,
    'totalPoints' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'explanation' : IDL.Text,
    'correct' : IDL.Bool,
    'pointsEarned' : IDL.Nat,
  });
  const ProfileUpdate = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'dob' : IDL.Opt(IDL.Text),
    'heightCm' : IDL.Opt(IDL.Float64),
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'lifeStage' : IDL.Opt(IDL.Text),
    'weightKg' : IDL.Opt(IDL.Float64),
  });
  
  return IDL.Service({
    'addCycleRecord' : IDL.Func([CycleRecord], [Result], []),
    'analyzeCurrentCycle' : IDL.Func([], [AnalysisResult], []),
    'getAverageCycleLength' : IDL.Func([], [IDL.Float64], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getCurrentCyclePrediction' : IDL.Func(
        [],
        [IDL.Opt(CyclePrediction)],
        ['query'],
      ),
    'getCycleHistory' : IDL.Func([], [IDL.Vec(CycleRecord)], ['query']),
    'getDailyLogs' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DailyLog)],
        ['query'],
      ),
    'getDailyQuizzes' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getLogForDate' : IDL.Func([IDL.Text], [IDL.Opt(DailyLog)], ['query']),
    'getMonthlyReport' : IDL.Func([], [MonthlyReport], []),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSelfCareForPhase' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SelfCareItem)],
        ['query'],
      ),
    'getUserProgress' : IDL.Func([], [UserProgress], ['query']),
    'saveDailyLog' : IDL.Func([DailyLog], [Result], []),
    'saveProfile' : IDL.Func([UserProfile], [Result], []),
    'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'submitQuizAnswer' : IDL.Func([IDL.Text, IDL.Nat], [QuizResult], []),
    'updateProfile' : IDL.Func([ProfileUpdate], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };