/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReport {
    nextSteps: string;
    avgPainLevel: number;
    patternInsight: string;
    cycleLength: bigint;
    commonSymptoms: Array<string>;
}
export interface CycleRecord {
    id: string;
    periodDays: bigint;
    cycleLengthDays: bigint;
    createdAt: bigint;
    notes?: string;
    startDate: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface ProfileUpdate {
    age?: bigint;
    dob?: string;
    heightCm?: number;
    city?: string;
    name?: string;
    lifeStage?: string;
    weightKg?: number;
}
export interface QuizQuestion {
    id: string;
    question: string;
    correctIndex: bigint;
    explanation: string;
    options: Array<string>;
}
export interface SelfCareItem {
    title: string;
    tips: Array<string>;
    description: string;
    category: string;
    phase: string;
}
export interface DailyLog {
    id: string;
    painLevel?: bigint;
    date: string;
    mood?: string;
    createdAt: bigint;
    notes?: string;
    symptoms: Array<string>;
}
export interface CyclePrediction {
    currentPhase: string;
    ovulationDate: string;
    dayOfCycle: bigint;
    fertileWindowStart: string;
    fertileWindowEnd: string;
    nextPeriodStart: string;
}
export interface QuizResult {
    explanation: string;
    correct: boolean;
    pointsEarned: bigint;
}
export interface ChatMessage {
    content: string;
    role: string;
    timestamp: bigint;
}
export interface AnalysisResult {
    guidanceLevel: string;
    delayDays?: bigint;
    reasoning: string;
    isNormal: boolean;
    guidance: string;
}
export interface UserProgress {
    lastQuizDate: string;
    totalCompleted: bigint;
    quizzesCompletedToday: bigint;
    totalPoints: bigint;
}
export interface UserProfile {
    id: Principal;
    age: bigint;
    dob?: string;
    heightCm: number;
    city: string;
    name: string;
    createdAt: bigint;
    lifeStage: string;
    weightKg: number;
}
export interface backendInterface {
    addCycleRecord(record: CycleRecord): Promise<Result>;
    analyzeCurrentCycle(): Promise<AnalysisResult>;
    getAverageCycleLength(): Promise<number>;
    getChatHistory(): Promise<Array<ChatMessage>>;
    getCurrentCyclePrediction(): Promise<CyclePrediction | null>;
    getCycleHistory(): Promise<Array<CycleRecord>>;
    getDailyLogs(startDate: string, endDate: string): Promise<Array<DailyLog>>;
    getDailyQuizzes(): Promise<Array<QuizQuestion>>;
    getLogForDate(date: string): Promise<DailyLog | null>;
    getMonthlyReport(): Promise<MonthlyReport>;
    getProfile(): Promise<UserProfile | null>;
    getSelfCareForPhase(phase: string): Promise<Array<SelfCareItem>>;
    getUserProgress(): Promise<UserProgress>;
    saveDailyLog(log: DailyLog): Promise<Result>;
    saveProfile(profile: UserProfile): Promise<Result>;
    sendChatMessage(message: string): Promise<string>;
    submitQuizAnswer(questionId: string, selectedIndex: bigint): Promise<QuizResult>;
    updateProfile(updates: ProfileUpdate): Promise<Result>;
}
import type { AnalysisResult as _AnalysisResult, CyclePrediction as _CyclePrediction, CycleRecord as _CycleRecord, DailyLog as _DailyLog, ProfileUpdate as _ProfileUpdate, Result as _Result, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCycleRecord(arg0: CycleRecord): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addCycleRecord(to_candid_CycleRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCycleRecord(to_candid_CycleRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async analyzeCurrentCycle(): Promise<AnalysisResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeCurrentCycle();
                return from_candid_AnalysisResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeCurrentCycle();
            return from_candid_AnalysisResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAverageCycleLength(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageCycleLength();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageCycleLength();
            return result;
        }
    }
    async getChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChatHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChatHistory();
            return result;
        }
    }
    async getCurrentCyclePrediction(): Promise<CyclePrediction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentCyclePrediction();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentCyclePrediction();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCycleHistory(): Promise<Array<CycleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCycleHistory();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCycleHistory();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyLogs(arg0: string, arg1: string): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyLogs(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyLogs(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyQuizzes(): Promise<Array<QuizQuestion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyQuizzes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyQuizzes();
            return result;
        }
    }
    async getLogForDate(arg0: string): Promise<DailyLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogForDate(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogForDate(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyReport(): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport();
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSelfCareForPhase(arg0: string): Promise<Array<SelfCareItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSelfCareForPhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSelfCareForPhase(arg0);
            return result;
        }
    }
    async getUserProgress(): Promise<UserProgress> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress();
            return result;
        }
    }
    async saveDailyLog(arg0: DailyLog): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyLog(to_candid_DailyLog_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyLog(to_candid_DailyLog_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveProfile(arg0: UserProfile): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChatMessage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return result;
        }
    }
    async submitQuizAnswer(arg0: string, arg1: bigint): Promise<QuizResult> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizAnswer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizAnswer(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: ProfileUpdate): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_ProfileUpdate_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_ProfileUpdate_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalysisResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisResult): AnalysisResult {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CycleRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleRecord): CycleRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_DailyLog_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DailyLog): DailyLog {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyLog]): DailyLog | null {
    return value.length === 0 ? null : from_candid_DailyLog_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CyclePrediction]): CyclePrediction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    periodDays: bigint;
    cycleLengthDays: bigint;
    createdAt: bigint;
    notes: [] | [string];
    startDate: string;
}): {
    id: string;
    periodDays: bigint;
    cycleLengthDays: bigint;
    createdAt: bigint;
    notes?: string;
    startDate: string;
} {
    return {
        id: value.id,
        periodDays: value.periodDays,
        cycleLengthDays: value.cycleLengthDays,
        createdAt: value.createdAt,
        notes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.notes)),
        startDate: value.startDate
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    painLevel: [] | [bigint];
    date: string;
    mood: [] | [string];
    createdAt: bigint;
    notes: [] | [string];
    symptoms: Array<string>;
}): {
    id: string;
    painLevel?: bigint;
    date: string;
    mood?: string;
    createdAt: bigint;
    notes?: string;
    symptoms: Array<string>;
} {
    return {
        id: value.id,
        painLevel: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.painLevel)),
        date: value.date,
        mood: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.mood)),
        createdAt: value.createdAt,
        notes: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.notes)),
        symptoms: value.symptoms
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    age: bigint;
    dob: [] | [string];
    heightCm: number;
    city: string;
    name: string;
    createdAt: bigint;
    lifeStage: string;
    weightKg: number;
}): {
    id: Principal;
    age: bigint;
    dob?: string;
    heightCm: number;
    city: string;
    name: string;
    createdAt: bigint;
    lifeStage: string;
    weightKg: number;
} {
    return {
        id: value.id,
        age: value.age,
        dob: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.dob)),
        heightCm: value.heightCm,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        lifeStage: value.lifeStage,
        weightKg: value.weightKg
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    guidanceLevel: string;
    delayDays: [] | [bigint];
    reasoning: string;
    isNormal: boolean;
    guidance: string;
}): {
    guidanceLevel: string;
    delayDays?: bigint;
    reasoning: string;
    isNormal: boolean;
    guidance: string;
} {
    return {
        guidanceLevel: value.guidanceLevel,
        delayDays: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.delayDays)),
        reasoning: value.reasoning,
        isNormal: value.isNormal,
        guidance: value.guidance
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DailyLog>): Array<DailyLog> {
    return value.map((x)=>from_candid_DailyLog_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CycleRecord>): Array<CycleRecord> {
    return value.map((x)=>from_candid_CycleRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_CycleRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CycleRecord): _CycleRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DailyLog_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DailyLog): _DailyLog {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ProfileUpdate_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfileUpdate): _ProfileUpdate {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    periodDays: bigint;
    cycleLengthDays: bigint;
    createdAt: bigint;
    notes?: string;
    startDate: string;
}): {
    id: string;
    periodDays: bigint;
    cycleLengthDays: bigint;
    createdAt: bigint;
    notes: [] | [string];
    startDate: string;
} {
    return {
        id: value.id,
        periodDays: value.periodDays,
        cycleLengthDays: value.cycleLengthDays,
        createdAt: value.createdAt,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        startDate: value.startDate
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    painLevel?: bigint;
    date: string;
    mood?: string;
    createdAt: bigint;
    notes?: string;
    symptoms: Array<string>;
}): {
    id: string;
    painLevel: [] | [bigint];
    date: string;
    mood: [] | [string];
    createdAt: bigint;
    notes: [] | [string];
    symptoms: Array<string>;
} {
    return {
        id: value.id,
        painLevel: value.painLevel ? candid_some(value.painLevel) : candid_none(),
        date: value.date,
        mood: value.mood ? candid_some(value.mood) : candid_none(),
        createdAt: value.createdAt,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        symptoms: value.symptoms
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    age: bigint;
    dob?: string;
    heightCm: number;
    city: string;
    name: string;
    createdAt: bigint;
    lifeStage: string;
    weightKg: number;
}): {
    id: Principal;
    age: bigint;
    dob: [] | [string];
    heightCm: number;
    city: string;
    name: string;
    createdAt: bigint;
    lifeStage: string;
    weightKg: number;
} {
    return {
        id: value.id,
        age: value.age,
        dob: value.dob ? candid_some(value.dob) : candid_none(),
        heightCm: value.heightCm,
        city: value.city,
        name: value.name,
        createdAt: value.createdAt,
        lifeStage: value.lifeStage,
        weightKg: value.weightKg
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    dob?: string;
    heightCm?: number;
    city?: string;
    name?: string;
    lifeStage?: string;
    weightKg?: number;
}): {
    age: [] | [bigint];
    dob: [] | [string];
    heightCm: [] | [number];
    city: [] | [string];
    name: [] | [string];
    lifeStage: [] | [string];
    weightKg: [] | [number];
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        dob: value.dob ? candid_some(value.dob) : candid_none(),
        heightCm: value.heightCm ? candid_some(value.heightCm) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        lifeStage: value.lifeStage ? candid_some(value.lifeStage) : candid_none(),
        weightKg: value.weightKg ? candid_some(value.weightKg) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
